### ISSUE TITLE
'LIKE' queries getting escaped

### ISSUE THREAD

**Issue by aviabrams** [itsumura-h/nim-allographer#127]
When I run a query like

rdb().table("people").select("name").where("name", "LIKE", "%Mark%").get()
the '%' gets escaped and returns no results.

The raw sql should be
`SELECT name FROM people WHERE name LIKE '%Mark%'`
instead the query becomes
`SELECT name FROM people WHERE name LIKE '\%Mark\%'`

So how to run queries with 'LIKE' ?

**Comment by sclee15** [comment]
use the following "LIKE","%LIKE","LIKE%","%LIKE%"

**Comment by itsumura-h** [comment]
@aviabrams 
You can now use LIKE in query
https://github.com/itsumura-h/nim-allographer/blob/master/tests/test_query.nim#L128-L133
