### ISSUE TITLE
Cannot change DB_DRIVER to mysql or postgres

### ISSUE THREAD

**Issue by ranedk** [itsumura-h/nim-allographer#154]
I am new to Nim, so please pardon my understanding.

## Issue
In the environment (or the .env file), DB_DRIVER=postgres won't change the DRIVER in `baseEnv.nim` and defaults to the value `sqlite` . So it's impossible to use the code for non-sqlite databases.
This is probably happening because inside `baseEnv.nim` DRIVER is defined as a `const`, which gets assigned during the compile time, where as dotenv reads the .env file in runtime.

## Fix
Define DRIVER as `let DRIVER`

## Suggestions
We may want to support multiple databases too, so taking out the connection logic from the package may be a good idea. This way, the package using it (I am trying to use this with Prologue framework) can define the initialization parameters using a more flexible approach.

**Comment by itsumura-h** [comment]
@ranedk 

When we use sqlite, `db_sqlite` of stdlib is used and we use mysql, `db_mysql` is used.
https://github.com/itsumura-h/nim-allographer/blob/master/src/allographer/connection.nim

If `DRIVER` is changed from `const` to `let`, it's broken.

I have a plan not to use stdlib but to use [this library](https://github.com/sivchari/async_db).
After replace core database library, your wish may be granted!
Thank you.
