### ISSUE TITLE
any plan provide api let driver developer can integrate nim-allographer with their own driver ?

### ISSUE THREAD

**Issue by bung87** [itsumura-h/nim-allographer#157]
currently driver are static choose between std libs.

**Comment by itsumura-h** [comment]
@bung87 
I have a plan to replace core library from std libs to [this](https://github.com/sivchari/async_db).
It will be able to choose driver dynamically.
This is in progress. Thank you!

**Comment by itsumura-h** [comment]
@bung87 
Now you can create multiple database connections like this.
https://github.com/itsumura-h/nim-allographer/blob/master/tests/connections.nim#L17-L22

```nim
let sqliteDb = = dbopen(SQLite3, ":memory:", maxConnections=maxConnections)
let pgDb = dbopen(PostgreSQL, database, user, password, pgHost, pgPort, maxConnections, timeout)

let huga = await sqliteConn.select("huga").first()
let piyo = await pgDb.select("piyo").first()
```
