### ISSUE TITLE
use chronos

### ISSUE THREAD

**Issue by itsumura-h** [itsumura-h/nim-allographer#173]
https://github.com/status-im/nim-chronos

**Comment by Yu-Vitaqua-fer-Chronos** [comment]
Assuming this won't be implemented?

**Comment by itsumura-h** [comment]
@Yu-Vitaqua-fer-Chronos 
I checked the performance of both `asyncdispatch` and `chronos` and found that `asyncdispatch` was faster, so I didn't implement it.

https://zenn.dev/dumblepy/articles/354a8873832a12#asyncdispatch-vs-chronos
