### ISSUE TITLE
Doesn't work on debian

### ISSUE THREAD

**Issue by ire4ever1190** [itsumura-h/nim-allographer#175]
Was getting a nil access error when trying to deploy a project using `v0.19.2` to a debian server even though it worked fine on my local machine. I think I tracked down the error to the way allographer checks if [sqlite exists](https://github.com/itsumura-h/nim-allographer/blob/faebaa73f7033c1ba8347a3bbcfd62a882b5cded/src/allographer/async/database/is_exists_lib.nim#L10) since `ldconfig` cannot be ran on debian without sudo so it silently fails if a normal user tries to build

I have removed [this line](https://github.com/itsumura-h/nim-allographer/blob/faebaa73f7033c1ba8347a3bbcfd62a882b5cded/src/allographer/async/async_db.nim#L21) and was able to get it working. Could a flag be added to disable the check or even remove it so that code will at least fail saying it cant find sqlite?

**Comment by itsumura-h** [comment]
@ire4ever1190 
Updated [v0.22.0](https://github.com/itsumura-h/nim-allographer/releases/tag/v0.22.0)

In your `config.nims`、If you write like bellow,
```nim
putEnv("DB_SQLITE", $true)
```
only process of sqlite will be compiled without checking by shell command.
