### ISSUE TITLE
Custom/composite primary keys

### ISSUE THREAD

**Issue by wayjack** [itsumura-h/nim-allographer#198]
Is there a way to set individual columns as primary key without needing to use `increments("id")`? Or composite primary keys?

**Comment by itsumura-h** [comment]
@xankz 
To set primary key, you have to use `increments("id")` or `uuid("uuid")`.  Automatic generation of implicit primary keys is not assumed.
But I'm going to add `primary()` option to implement composite primary keys.

```
rdb.create(
  table("users", [
    Column.increments("id"),
    Column.string("name").primary(),
    Column.string("email").primary(),
  ])
)
```
