### ISSUE TITLE
support for whereIn for strings

### ISSUE THREAD

**Issue by gowthaman-basuvaraj** [itsumura-h/nim-allographer#223]
at present whereIn can take seq of only int and float, can it be extended to take seq of strings as well

Thank you

**Comment by itsumura-h** [comment]
@gowthaman-basuvaraj 
I released a new version including PR #224 
You can now update allographer and able to use whereIn procs.

https://github.com/itsumura-h/nim-allographer/releases/tag/v0.24.1
