### ISSUE TITLE
Inserting binary data into BLOB column in sqlite fails with "unhandled exception: unrecognized token" 

### ISSUE THREAD

**Issue by sgmihai** [itsumura-h/nim-allographer#235]
Just like the error here: https://github.com/nim-lang/db_connector/issues/12
Code to reproduce:

```
import asyncdispatch, httpclient, json
import allographer/[connection, schema_builder, query_builder]

proc createTable(myDb: Rdb) {.async.} =
  myDb.create([
    table("mytable", [
      Column.uuid("id"),
      Column.binary("blob").nullable()
    ])
  ])

proc main() {.async.} =
  let myDb = dbOpen(Sqlite3, "mydb.db", maxConnections=10, timeout=30)
  await createTable(myDb)

  let binFile = newHttpClient().getContent("https://cdimage.debian.org/debian-cd/current/amd64/bt-cd/debian-11.7.0-amd64-netinst.iso.torrent")
  let data = %*{
    "id": 1,
    "blob": binFile
    }
  
  myDb.table("mytable").insert(data).await

waitFor main()

**Comment by sgmihai** [comment]
I found this commit that was not merged for some reason. 6 year old problem, very sad for nim:
https://github.com/nim-lang/Nim/commit/6fa82a5b3afbe644eef3fb41647a341d8e9b21c4

**Comment by itsumura-h** [comment]
@sgmihai 
I wrote a low-level sample code. It works fine 💪

https://github.com/itsumura-h/nim-allographer/blob/235-inserting-binary-data-into-blob-column-in-sqlite-fails-with-unhandled-exception-unrecognized-token/example/sqlite_binary.nim

**Comment by sgmihai** [comment]
Thank you, I will try to implement it.
But what about fixing it in allographer ?

**Comment by itsumura-h** [comment]
@sgmihai 
I have not yet made changes to allogrpher itself. I will work on it later. Please wait for a few days.
